DROP TABLE IF EXISTS orders_clean;

CREATE TABLE orders_clean (
    order_id TEXT PRIMARY KEY,
    customer_id TEXT,
    rider_id TEXT,
    dark_store_id TEXT,
    order_timestamp TEXT,
    weather TEXT,
    traffic_density TEXT,
    vehicle_type TEXT,
    primary_category TEXT,
    payment_method TEXT,
    total_items INTEGER,
    delivery_distance_km REAL,
    order_value_inr REAL,
    is_local_rider TEXT,
    pack_time_mins REAL,
    transit_time_mins REAL,
    total_delivery_time_mins REAL,
    sla_breached INTEGER,
    rider_rating_raw TEXT,
    order_date TEXT,
    order_hour INTEGER,
    day_name TEXT,
    week INTEGER,
    rider_rating REAL,
    delivery_speed_kmph REAL,
    revenue_per_km REAL,
    delivery_bucket TEXT,
    distance_bucket TEXT
);
